FROM node:16.14-alpine3.15

ARG APP_VERSION=1.0.0
ARG NODE_ENV=development

ENV NODE_ENV=${NODE_ENV}
ENV NESTJS_PORT=8080

WORKDIR /usr/app

RUN npm i -g @nestjs/cli

USER node

ENV APP_VERSION=${APP_VERSION}

CMD ["npm", "run", "start:dev"]