apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: omni-catalog-api-hpa
  labels:
    app: omni-catalog-api
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: omni-catalog-api-deployment
 minReplicas: 3
 maxReplicas: 8
 targetCPUUtilizationPercentage: 50