apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../base
resources:
  - namespace.yaml
patchesStrategicMerge:
  - namespace.yaml
  - deployment.yaml
  - hpa.yaml
namespace: omni-catalog-api-local
images:
  - name: omni-catalog-api
    newTag: 2022.04.09.220942
